- name: Specify MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{mysql_root_password | quote}}' vtype='password'
  become: true

- name: Confirm MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysql_root_password | quote}}' vtype='password'
  become: true

- name: Install required dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python
    - python-setuptools
    - python-dev
    - build-essential
    - python-pip
    - python-pymysql

- name: Install MySQL dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - mysql-common
    - mysql-server
    - mysql-client

- name: Start MySQL Service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Copy initial MySQL client config file, no password, for root
  copy:
    src: ../templates/.my.cnf
    dest: /root/.my.cnf

- name: update mysql root password for all root accounts
  become: true
  mysql_user:
    name: root
    host: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    password: "{{ lookup('cypher','secret=secret/MYSQL_ROOT_PWD') }}"
    login_user: root
    login_password: "{{ lookup('cypher','secret=secret/MYSQL_ROOT_PWD') }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
    - "{{ ansible_host }}"

- name: Create `/root/.my.cnf` with root password credentials
  become: yes
  template:
    src: ../templates/.my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
